name: continuous-deployment-workflow

on:
  push:
    branches:
      - fix/docker

env:
  NODE_VERSION: 12.20.1

jobs:
  build-and-publish-to-dockerhub:
    runs-on: ubuntu-latest
    environment: CustomerReviewAnalyzer.Node-Prod
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            node_version=12.20.1
            environment=production
          push: true
          tags: gavindebruyn/customer-review-analyzer-node:latest
